config/routes.rb
Rails.application.routes.draw do
  
  root 'band#landing'
  resources :posts do
    resources :comments
  end
  resources :photos, :chronicles
  
  
  get 'landing' => 'band#landing', :as => :landing
  get 'admin' => 'posts#admin', :as => :admin
  get 'gallery' => 'band#gallery',:as => :gallery
  get 'members' => 'band#members', :as => :members
  get 'join' => 'band#join', :as => :join
  get 'contact' => 'band#contact', :as => :contact
  
end

app/models/chronicle.rb
class Chronicle < ActiveRecord::Base
	validates :title, presence: true, length: { minimum: 5 }, on: :create
	validates :body,  presence: true, length: { minimum: 5 }, on: :create
	mount_uploader :image, ImageUploader
end

app/models/comment.rb
class Comment < ActiveRecord::Base
    belongs_to :post
end

app/models/photo.rb
class Photo < ActiveRecord::Base
    mount_uploader :photo, ImageUploader
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments, dependent: :destroy
	validates :title, presence: true, length: { minimum: 5 }, on: :create
	validates :body,  presence: true, length: { minimum: 5 }, on: :create
	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/band_controller.rb
class BandController < ApplicationController
    
    def landing
    end
    
    def contact
    end
    
    def gallery
    end
    
    def members
    end
    
    def story
    end
    
    def join
    end
end

app/controllers/chronicles_controller.rb
class ChroniclesController < ApplicationController
  before_action :find_chronicle, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: 'x', password: 'x', except: [:index, :show]
  
  def new
    @chronicle = Chronicle.new
  end
  
  def create
    @chronicle = Chronicle.new(allowed_params)
      
    if @chronicle.save
      flash[:success] = "Wpis utworzony"
      redirect_to chronicles_path
    else
      flash[:alert] = "Wpis nie został utworzony"
      render 'new'
    end
  end
  
  def show
  end
  
  def index
    @chronicles = Chronicle.all
  end
  
  def edit
  end
  
  def admin
    @chronicles = Chronicles.all
  end
  
  def update
    if @chronicle.update_attributes(allowed_params)
      flash[:success] = "Wpis zedytowany"
      redirect_to chronicles_path
    else
      flash[:alert] = "Wpis nie został zedytowany"
      render 'new'
    end
  end
  
  def destroy
    @chronicle.destroy
      flash[:success] = "Wpis usunięty"
      redirect_to chronicles_admin_path
  end

private

  def find_chronicle
    @chronicle = Chronicle.find(params[:id])
  end

  def allowed_params
    params.require(:chronicle).permit(:title, :body, :image)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.new(params[:comment].permit(:name, :body))
		@comment.save

		respond_to do |format|
			format.html { redirect_to @post }
			format.js
		end
	end

	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		flash[:success] = "Komentarz usunięty!"
		redirect_to @post
	end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  http_basic_authenticate_with name: 'x', password: 'x', except: [:index, :show]
    
  def new
    @photo = Photo.new
  end
  
  def create
    @post = Photo.new(allowed_params)
      
    if @post.save
      flash[:success] = "Zdjęcie dodane"
      redirect_to photos_path
    else
      flash[:alert] = "Nie udało się dodać zdjęcia"
      render 'new'
    end
  end
  
  def index
    @photos = Photo.all
  end
  
  def show
    @photo = Photo.find(params[:id])
  end
  
  private
  
  def allowed_params
    params.require(:photo).permit(:photo)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  http_basic_authenticate_with name: 'x', password: 'x', except: [:index, :show]
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(allowed_params)
      
    if @post.save
      flash[:success] = "Post utworzony"
      redirect_to posts_path
    else
      flash[:alert] = "Post nie został utworzony"
      render 'new'
    end
  end
  
  def show
  end
  
  def index
    @posts = Post.all
  end
  
  def edit
   # @post = Post.find(params[:id])
  end
  
  def admin
    @posts = Post.all
  end
  
  def update
    if @post.update_attributes(allowed_params)
      flash[:success] = "Post zedytowany"
      redirect_to posts_path
    else
      flash[:alert] = "Post nie został zedytowany"
      render 'new'
    end
  end
  
  def destroy
    @post.destroy
      flash[:success] = "Post usunięty"
      redirect_to posts_path
  end

private

  def find_post
    @post = Post.find(params[:id])
  end

  def allowed_params
    params.require(:post).permit(:title, :body, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def bootstrap_class_for flash_type
    case flash_type
      when "success"
        "alert-success"   # Green
      when "error"
        "alert-danger"    # Red
      when "alert"
        "alert-warning"   # Yellow
      when "notice"
        "alert-info"      # Blue
      else
        flash_type.to_s
    end
  end
end

app/helpers/band_helper.rb
module BandHelper
end

app/helpers/chronicles_helper.rb
module ChroniclesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/band/contact.html.erb
<h2>Contact</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>

app/views/band/gallery.html.erb
<h2>Galeria</h2>
<div class="gallery">
<h2>Koncert noworoczny w Bukowcu</h2>
<iframe width="500" height="281" src="https://www.youtube.com/embed/OBBu1nGMV_E" frameborder="0" allowfullscreen></iframe>
<h2>Muzyczne Lato w Woli Rakowej 2009</h2>
<iframe width="500" height="281" src="https://www.youtube.com/embed/HIFKnzsjyKs" frameborder="0" allowfullscreen></iframe>
<h2>Muzyczne Lato w Woli Rakowej 2010</h2>
<iframe width="500" height="281" src="https://www.youtube.com/embed/xFG0MNqJ_4A" frameborder="0" allowfullscreen></iframe>
<h2>Muzyczne Lato w Woli Rakowej 2011</h2>
<iframe width="500" height="281" src="https://www.youtube.com/embed/jBLbleL4S4I" frameborder="0" allowfullscreen></iframe>
</div>

app/views/band/join.html.erb
<h2>Dołącz do Nas!</h2>

app/views/band/landing.html.erb
<h2>Strona startowa</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>

app/views/band/members.html.erb
<h2>Skład zespołu</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>

app/views/band/story.html.erb
<h2>Contact</h2>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."</p>

app/views/chronicles/admin.html.erb
<%= link_to 'Utwórz Post', new_post_path, class: "h2 glyphicon glyphicon-pencil" %>
<% @posts.each do |post| %>
    <p>
       <h2>Tytuł: <%= link_to post.title, post_path(post) %></h2>  </br>
       <%= post.body %></p>
       <%= link_to 'Edytuj', edit_post_path(post) %> |
       <%= link_to 'Usuń', post, method: :delete, data: { confirm:"You are about to destroy this post, are you sure?" }  %> |</br>
       <% if post.image_url != nil %>
			<%= image_tag post.image_url(:thumb).to_s %>
		<% end %>
			<%= render post.comments %>
<% end %>

app/views/chronicles/edit.html.erb
<%= form_for @post, :html => {:multipart => true} do |f| %>
    <%= f.label :nazwa %> </br>
    <%= f.text_area(:title, cols: 60, class: "textarea") %> </br>

    <%= f.label :tekst %> </br>
    <%= f.text_area(:body, cols: 60, rows: 15, class: "textarea") %> </br>
    
    <%= f.file_field :image %> </br>

    <%= f.submit "Edytuj post", class: "btn btn-success" %>
<% end %>

app/views/chronicles/index.html.erb
<h2>Aktualności</h2>
<% @chronicles.each do |chronicle| %>
    <p>
       <h2><%= link_to chronicle.title, chronicle_path(chronicle) %></h2> </br>
       <%= chronicle.body %>
    </p>
    <% if chronicle.image != nil %>
	    <%= image_tag chronicle.image_url(:thumb).to_s %>
	<% end %>
<% end %>

app/views/chronicles/new.html.erb
<%= form_for @chronicle, :html => {:multipart => true} do |f| %>
    <%= f.label :nazwa %> </br>
    <%= f.text_area(:title, cols: 60, class: "textarea") %> </br>

    <%= f.label :tekst %> </br>
    <%= f.text_area(:body, cols: 60, rows: 15, class: "textarea") %> </br>
    
    <%= f.file_field :image %> </br>

    <%= f.submit "Utwórz wpis", class: "btn btn-success" %>
<% end %>

app/views/chronicles/show.html.erb
<div class="body-wrapper" style="padding-bottom: 0px; border-bottom: 1px solid #d6dce0; width: 550px">
	<h2><%= @chronicle.title %></h2> </br>
	<%= @chronicle.body %> </br>
	<% if @chronicle.image_url != nil %>
		<%= image_tag @chronicle.image_url(:thumb).to_s %>
	<% end %>
</div>

app/views/comments/_comment.html.erb
</br>
<span>Użytkownik <strong><%= comment.name %></strong> napisał: </span><span style='float: right; margin-right: 50px'>Dodano dnia: <%= comment.created_at.strftime("%Y-%m-%d") %></span>
<div class="comment-container well well-sm">
<p><%= comment.body %></p>
</div>

app/views/comments/_form.html.erb
<%= form_for [@post, @post.comments.build] do |f| %>
    <p>
        <%= f.label :autor %>
        <%= f.text_field :name, placeholder: "Podpisz się" %></br>
        <%= f.label :tekst %>
        <%= f.text_area(:body, cols: 60, class: "textarea", placeholder: "Napisz coś") %></br>
        <%= f.button "Skomentuj", class: "btn btn-info" %>
    </p>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |type, message| %>
  <div class="alert <%= bootstrap_class_for(type) %> fade in">
    <button class="close" data-dismiss="alert">×</button>
    <%= message %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="row">
    <div class='title col-xs-12'>
        <div class="footer">
          <div class="col-xs-0 col-md-2 col-lg-3"></div>
          <div class='title col-xs-12 col-md-8'>
            <p style="margin: 10px;">Nam strzelać nie kazano. - Wstąpiłem na działo
            I spójrzałem na pole; dwieście armat grzmiało.</p>
            </div>
        </div>
    </div>
</div>
<div class="row", id="copywright" >
    <div class='title col-xs-12'>
        <div class="col-xs-0 col-md-2 col-lg-3"></div>
        <div class='title col-xs-12 col-md-8'>
            <span style="margin: 10px">@Orkiestra OSP Kurowice 2016</span>
            <span style='position: relative; right: -300px'>
                Design Adam Żaczek
            </span>
        </div>
    </div>
</div>

app/views/layouts/_nav.html.erb
<div class="header">
<div class="row", id="top2">
    <div class='title col-xs-12 col-md-3'>
        <%= link_to "Orkiestra OSP Kurowice", root_path, class: "h1" %>
    </div>
    <div class="topmenu col-xs-12 col-md-9">
        <div id='fb'>
        <div class="fb-page" data-href="https://www.facebook.com/orkiestrakurowice/?ref=ts&amp;fref=ts" data-width="500" data-height="70" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><div class="fb-xfbml-parse-ignore"><blockquote cite="https://www.facebook.com/orkiestrakurowice/?ref=ts&amp;fref=ts"><a href="https://www.facebook.com/orkiestrakurowice/?ref=ts&amp;fref=ts">Orkiestra OSP Kurowice</a></blockquote></div></div></div></br>
        <div class="links">
        <%= link_to "Aktualności", posts_path %>
        <%= link_to "Historia", members_path %>
        <%= link_to "Skład zespołu", join_path %>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <p>Galeria</p>
        </a>
        <ul class="dropdown-menu", style="margin-left: 280px;">
        <%= link_to "Zdjęcia", photos_path, id: '1' %>
        <%= link_to "Nagrania", gallery_path, id: '2' %>
            </ul>
        <%= link_to "Kontakt", members_path %>
        </div>
    </div>
</div>
</div>

app/views/layouts/_youtube.html.erb
<div class="you">
    <%= link_to "Zdjęcia", photos_path, class: "h3" %>
    <div>
        <%= link_to image_tag("1917.jpg", :class => 'img'), photos_path %> 
    </div>
    
    <%= link_to "Nagrania", gallery_path, class: "h3" %>
    <h4>Muzyczne Lato w Woli Rakowej 2011</h4>    
    <iframe width="200" height="113" src="https://www.youtube.com/embed/jBLbleL4S4I" frameborder="0" allowfullscreen></iframe>
    
    <h4>Muzyczne Lato w Woli Rakowej 2010</h4>
    <iframe width="200" height="113" src="https://www.youtube.com/embed/xFG0MNqJ_4A" frameborder="0" allowfullscreen></iframe>
    
    <h4>Muzyczne Lato w Woli Rakowej 2009</h4>
    <iframe width="200" height="113" src="https://www.youtube.com/embed/HIFKnzsjyKs" frameborder="0" allowfullscreen></iframe>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
          <title>Orkiestra OSP Kurowice</title>
          <%= stylesheet_link_tag    'application', media: 'all' %>
          <%= javascript_include_tag 'application' %>
          <link href='http://fonts.googleapis.com/css?family=Crimson+Text' rel='stylesheet' type='text/css'>
          <link href='http://fonts.googleapis.com/css?family=Allerta' rel='stylesheet' type='text/css'>
          <link href="app/assets/stylesheets/lightbox.css.scss" rel="stylesheet">
          <%= csrf_meta_tags %>
    </head>
    <body>
    <div id="fb-root"></div>
    <script>
        (function(d, s, id) {
          var js, fjs = d.getElementsByTagName(s)[0];
          if (d.getElementById(id)) return;
          js = d.createElement(s); js.id = id;
          js.src = "//connect.facebook.net/pl_PL/sdk.js#xfbml=1&version=v2.5";
          fjs.parentNode.insertBefore(js, fjs);
        }(document, 'script', 'facebook-jssdk'));
    </script>
    <div class="row">
        <div class="col-xs-12">
            <%= render '/layouts/flash', flash: flash %>
        </div>
    </div>
    <div id='top'>
    <%= render '/layouts/nav' %>
    <div class="images">
  		<%= image_tag "band.jpg", id: "img" %>
 	</div>
 	</div>
	<div class="row">
  	    <div class="col-xs-0 col-md-1 col-lg-2 col-xlg-3"></div>
        <div class='title col-xs-12 col-md-9 col-lg-8 col-xlg-6'>
  		    <div class="body-wrapper">
  		        <div class="row" style="margin-left: 10px">
                    <div class='title col-xs-9 col-md-9 col-lg-8'>
                        <%= yield %>
                    </div>
                    <div class="col-xs-3 col-md-3 col-lg-3">
                        <%= render 'layouts/youtube' %>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <%= render 'layouts/footer' %>
    <script src="app/assets/javascripts/lightbox.js"></script>
    </body>
</html>

app/views/photos/index.html.erb
<h2>Witamy w naszej galerii</h2>
<div style="padding-left: 25px">
<% @photos.each do |photo| %>
    <a class="example-image-link" href="
    <%= photo.photo_url.to_s %>" data-lightbox: "gal" >
    <%= image_tag photo.photo_url(:gall).to_s, 
    style: "margin-bottom: 250px;", class: "example-image" %></a>
<% end %>
</div>

app/views/photos/new.html.erb
<%= form_for @photo, :html => {:multipart => true} do |f| %>
  <%= f.file_field :photo %>
  <%= f.submit "Dodaj zdjęcie", class: "btn btn-success" %>
<% end %>

app/views/photos/show.html.erb
<a href="<%= image_tag @photo.photo_url.to_s %>" data-lightbox="gal"><%= image_tag @photo.photo_url(:thumb).to_s %></a>

app/views/posts/index.html.erb
<h2>Aktualności</h2>
<% @posts.each do |post| %>
    <p>
       <h2><%= link_to post.title, post_path(post) %></h2> </br>
       <%= post.body %>
    </p>
    <% if post.image_url != nil %>
	    <%= image_tag post.image_url(:thumb).to_s %>
	<% end %>
	<%= render post.comments %> </br>
<% end %>

app/views/posts/new.html.erb
<%= form_for @post, :html => {:multipart => true} do |f| %>
    <%= f.label :nazwa %> </br>
    <%= f.text_area(:title, cols: 60, class: "textarea") %> </br>

    <%= f.label :tekst %> </br>
    <%= f.text_area(:body, cols: 60, rows: 15, class: "textarea") %> </br>
    
    <%= f.file_field :image %> </br>

    <%= f.submit "Utwórz post", class: "btn btn-success" %>
<% end %>

app/views/posts/show.html.erb
<div class="body-wrapper" style="padding-bottom: 0px; border-bottom: 1px solid #d6dce0; width: 550px">
	<h2><%= @post.title %></h2> </br>
	<%= @post.body %> </br>
	<% if @post.image_url != nil %>
		<%= image_tag @post.image_url(:thumb).to_s %>
	<% end %>
	<%= render @post.comments %>
	<%= render 'comments/form' %>
</div>